In [7]:
# task 1 

import numpy as np

def array_factory(mode, shape, value=None):
   
        if mode == "zeros":
            return np.zeros(shape)
        elif mode == "ones":
            return np.ones(shape)
        elif mode == "full":
            if value is None:
                raise ValueError("must provide value")
            return np.full(shape, value)
        elif mode == "identity":
            return np.eye(shape)
        else:
            raise ValueError(f"unknown mode: {mode}")
    
print(array_factory("zeros",(2,3)))
print(array_factory("ones",4))
print(array_factory("full", (2, 2), 7))
print(array_factory("identity",3))
    
    


[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# task 2 
import numpy as np



def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        reshaped_arr2 = arr2.reshape(-1, reshaped_arr1.shape[1])
        return np.vstack((reshaped_arr1, reshaped_arr2))
    except ValueError as e:
        raise ValueError(f"grade_error: {e}")

data2 = [1, 2, 3, 4, 5, 6]
data1 = [[7, 8, 9], [11, 12, 13]]
result= secure_reshape_and_stack(data1,data2,(2,3))
print(result)


[[ 7  8  9]
 [11 12 13]
 [ 1  2  3]
 [ 4  5  6]]


In [20]:
# part 3
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr
data = [1,5,8,2,9,3]
result = apply_threshold(data,threshold=5,replacement_value=-1)
print(result)


[ 1 -1 -1  2 -1  3]
